export const timezoneMapping: { zone: string; utc: string; name: string }[] = [
  { zone: "Asia/Baku", utc: "(GMT+04:00)", name: "Azerbaijan" },
  { zone: "Asia/Yerevan", utc: "(GMT+04:00)", name: "Armenia" },
  { zone: "America/Antigua", utc: "(GMT-04:00)", name: "Antigua and Barbuda" },
  { zone: "Europe/Andorra", utc: "(GMT+01:00)", name: "Andorra" },
  { zone: "Pacific/Pago_Pago", utc: "(GMT-11:00)", name: "American Samoa" },
  { zone: "Pacific/Midway", utc: "(GMT-11:00)", name: "Midway Island" },
  { zone: "US/Samoa", utc: "(GMT-11:00)", name: "Samoa" },
  { zone: "US/Hawaii", utc: "(GMT-10:00)", name: "Hawaii" },
  { zone: "US/Alaska", utc: "(GMT-09:00)", name: "Alaska" },
  { zone: "US/Pacific", utc: "(GMT-08:00)", name: "Pacific Time (US & Canada)" },
  { zone: "America/Toronto", utc: "(GMT-05:00)", name: "Eastern Time (Canada)" },
  { zone: "America/Edmonton", utc: "(GMT-07:00)", name: "Mountain Time (Canada)" },
  { zone: "America/Vancouver", utc: "(GMT-08:00)", name: "Pacific Time (Canada)" },
  { zone: "America/Tijuana", utc: "(GMT-08:00)", name: "Tijuana" },
  { zone: "Europe/Tirane", utc: "(GMT+1:00)", name: "Albania" },
  { zone: "US/Arizona", utc: "(GMT-07:00)", name: "Arizona" },
  { zone: "US/Mountain", utc: "(GMT-07:00)", name: "Mountain Time (US & Canada)" },
  { zone: "America/Chihuahua", utc: "(GMT-07:00)", name: "Chihuahua" },
  { zone: "America/Mazatlan", utc: "(GMT-07:00)", name: "Mazatlan" },
  { zone: "America/Mexico_City", utc: "(GMT-06:00)", name: "Mexico City" },
  { zone: "America/Monterrey", utc: "(GMT-06:00)", name: "Monterrey" },
  { zone: "America/Nassau", utc: "(GMT-05:00)", name: "Bahamas" },
  { zone: "Canada/Saskatchewan", utc: "(GMT-06:00)", name: "Saskatchewan" },
  { zone: "US/Central", utc: "(GMT-06:00)", name: "Central Time (US & Canada)" },
  { zone: "US/Eastern", utc: "(GMT-05:00)", name: "Eastern Time (US & Canada)" },
  { zone: "US/East-Indiana", utc: "(GMT-05:00)", name: "Indiana (East)" },
  { zone: "America/Bogota", utc: "(GMT-05:00)", name: "Bogota" },
  { zone: "America/Lima", utc: "(GMT-05:00)", name: "Lima" },
  { zone: "America/Caracas", utc: "(GMT-04:30)", name: "Caracas" },
  { zone: "Canada/Atlantic", utc: "(GMT-04:00)", name: "Atlantic Time (Canada)" },
  { zone: "America/La_Paz", utc: "(GMT-04:00)", name: "La_Paz" },
  { zone: "America/Santiago", utc: "(GMT-04:00)", name: "Santiago" },
  { zone: "Canada/Newfoundland", utc: "(GMT-03:30)", name: "Newfoundland" },
  { zone: "America/Buenos_Aires", utc: "(GMT-03:00)", name: "Buenos Aires" },
  { zone: "Greenland", utc: "(GMT-03:00)", name: "Greenland" },
  { zone: "Atlantic/Stanley", utc: "(GMT-02:00)", name: "Stanley" },
  { zone: "Atlantic/Azores", utc: "(GMT-01:00)", name: "Azores" },
  { zone: "Atlantic/Cape_Verde", utc: "(GMT-01:00)", name: "Cape Verde Is." },
  { zone: "Africa/Casablanca", utc: "(GMT)", name: "Casablanca" },
  { zone: "Europe/Dublin", utc: "(GMT)", name: "Dublin" },
  { zone: "Europe/Lisbon", utc: "(GMT)", name: "Lisbon" },
  { zone: "Europe/London", utc: "(GMT)", name: "London" },
  { zone: "Africa/Monrovia", utc: "(GMT)", name: "Monrovia" },
  { zone: "Europe/Amsterdam", utc: "(UTC+01:00)", name: "Amsterdam" },
  { zone: "Europe/Belgrade", utc: "(UTC+01:00)", name: "Belgrade" },
  { zone: "Europe/Berlin", utc: "(UTC+01:00)", name: "Berlin" },
  { zone: "Europe/Bratislava", utc: "(UTC+01:00)", name: "Bratislava" },
  { zone: "Europe/Brussels", utc: "(UTC+01:00)", name: "Brussels" },
  { zone: "Europe/Budapest", utc: "(UTC+01:00)", name: "Budapest" },
  { zone: "Europe/Copenhagen", utc: "(UTC+01:00)", name: "Copenhagen" },
  { zone: "Europe/Ljubljana", utc: "(UTC+01:00)", name: "Ljubljana" },
  { zone: "Europe/Madrid", utc: "(UTC+01:00)", name: "Madrid" },
  { zone: "Europe/Paris", utc: "(UTC+01:00)", name: "Paris" },
  { zone: "Europe/Rome", utc: "(UTC+01:00)", name: "Rome" },
  { zone: "Europe/Sarajevo", utc: "(UTC+01:00)", name: "Sarajevo" },
  { zone: "Europe/Skopje", utc: "(UTC+01:00)", name: "Skopje" },
  { zone: "Europe/Stockholm", utc: "(UTC+01:00)", name: "Stockholm" },
  { zone: "America/Montevideo", utc: "(GMT-03:00)", name: "Montevideo" },
  { zone: "Asia/Tashkent", utc: "(GMT+05:00)", name: "Tashkent" },
  { zone: "Europe/Vienna", utc: "(UTC+01:00)", name: "Vienna" },
  { zone: "Europe/Warsaw", utc: "(UTC+01:00)", name: "Warsaw" },
  { zone: "Europe/Zagreb", utc: "(UTC+01:00)", name: "Zagreb" },
  { zone: "Europe/Athens", utc: "(UTC+02:00)", name: "Athens" },
  { zone: "Europe/Bucharest", utc: "(UTC+02:00)", name: "Bucharest" },
  { zone: "Africa/Harare", utc: "(UTC+02:00)", name: "Harare" },
  { zone: "Europe/Helsinki", utc: "(UTC+02:00)", name: "Helsinki" },
  { zone: "Europe/Istanbul", utc: "(UTC+02:00)", name: "Istanbul" },
  { zone: "Asia/Jerusalem", utc: "(UTC+02:00)", name: "Jerusalem" },
  { zone: "Europe/Kiev", utc: "(UTC+02:00)", name: "Kiev" },
  { zone: "Europe/Minsk", utc: "(UTC+02:00)", name: "Minsk" },
  { zone: "Europe/Riga", utc: "(UTC+02:00)", name: "Riga" },
  { zone: "Europe/Sofia", utc: "(UTC+02:00)", name: "Sofia" },
  { zone: "Europe/Tallinn", utc: "(UTC+02:00)", name: "Tallinn" },
  { zone: "Europe/Vilnius", utc: "(UTC+02:00)", name: "Vilnius" },
  { zone: "Asia/Baghdad", utc: "(UTC+03:00)", name: "Baghdad" },
  { zone: "Asia/Kuwait", utc: "(UTC+03:00)", name: "Kuwait" },
  { zone: "America/Jamaica", utc: "(UTC-05:00)", name: "Jamaica" },
  { zone: "Asia/Riyadh", utc: "(UTC+03:00)", name: "Riyadh" },
  { zone: "Africa/Nairobi", utc: "(UTC+03:00)", name: "Nairobi" },
  { zone: "Asia/Tehran", utc: "(UTC+03:30)", name: "Tehran" },
  { zone: "Asia/Muscat", utc: "(UTC+04:00)", name: "Muscat" },
  { zone: "Asia/Dubai", utc: "(UTC+04:00)", name: "Dubai" },
  { zone: "Asia/Baku", utc: "(UTC+04:00)", name: "Baku" },
  { zone: "Europe/Moscow", utc: "(UTC+04:00)", name: "Moscow" },
  { zone: "Asia/Kabul", utc: "(UTC+04:30)", name: "Kabul" },
  { zone: "Asia/Tashkent", utc: "(UTC+05:00)", name: "Tashkent" },
  { zone: "Asia/Dushanbe", utc: "(GMT+05:00)", name: "Tajikistan" },
  { zone: "Asia/Yekaterinburg", utc: "(UTC+05:00)", name: "Yekaterinburg" },
  { zone: "Asia/Karachi", utc: "(UTC+05:00)", name: "Karachi" },
  { zone: "Asia/Kolkata", utc: "(UTC+05:30)", name: "Kolkata" },
  { zone: "Asia/Colombo", utc: "(UTC+05:30)", name: "Colombo" },
  { zone: "Asia/Kathmandu", utc: "(UTC+05:45)", name: "Kathmandu" },
  { zone: "Asia/Dhaka", utc: "(UTC+06:00)", name: "Dhaka" },
  { zone: "Asia/Almaty", utc: "(UTC+06:00)", name: "Almaty" },
  { zone: "Asia/Novosibirsk", utc: "(UTC+06:00)", name: "Novosibirsk" },
  { zone: "Asia/Rangoon", utc: "(UTC+06:30)", name: "Rangoon" },
  { zone: "Asia/Bangkok", utc: "(UTC+07:00)", name: "Bangkok" },
  { zone: "Asia/Jakarta", utc: "(UTC+07:00)", name: "Jakarta" },
  { zone: "Asia/Krasnoyarsk", utc: "(UTC+07:00)", name: "Krasnoyarsk" },
  { zone: "Asia/Shanghai", utc: "(UTC+08:00)", name: "Beijing" },
  { zone: "Asia/Chongqing", utc: "(UTC+08:00)", name: "Chongqing" },
  { zone: "Asia/Hong_Kong", utc: "(UTC+08:00)", name: "Hong Kong" },
  { zone: "Asia/Urumqi", utc: "(UTC+08:00)", name: "Urumqi" },
  { zone: "Asia/Irkutsk", utc: "(UTC+08:00)", name: "Irkutsk" },
  { zone: "Asia/Ulaanbaatar", utc: "(UTC+08:00)", name: "Ulaan Bataar" },
  { zone: "Asia/Kuala_Lumpur", utc: "(UTC+08:00)", name: "Kuala Lumpur" },
  { zone: "Asia/Singapore", utc: "(UTC+08:00)", name: "Singapore" },
  { zone: "Asia/Taipei", utc: "(UTC+08:00)", name: "Taipei" },
  { zone: "Asia/Bahrain", utc: "(GMT+03:00)", name: "Bahrain" },
  { zone: "America/Belize", utc: "(GMT-06:00)", name: "Belize" },
  { zone: "America/Barbados", utc: "(GMT-04:00)", name: "Barbados" },
  { zone: "Europe/Minsk", utc: "(GMT+03:00)", name: "Belarus" },
  { zone: "Africa/Porto-Novo", utc: "(GMT+01:00)", name: "Benin" },
  { zone: "America/La_Paz", utc: "(GMT-04:00)", name: "Bolivia" },
  { zone: "Europe/Sarajevo", utc: "(GMT+01:00)", name: "Bosnia and Herzegovina" },
  { zone: "Australia/Perth", utc: "(UTC+08:00)", name: "Perth" },
  { zone: "Asia/Seoul", utc: "(UTC+09:00)", name: "Seoul" },
  { zone: "Asia/Tokyo", utc: "(UTC+09:00)", name: "Tokyo" },
  { zone: "Asia/Yakutsk", utc: "(UTC+09:00)", name: "Yakutsk" },
  { zone: "Australia/Darwin", utc: "(UTC+09:30)", name: "Darwin" },
  { zone: "Australia/Adelaide", utc: "(UTC+09:30)", name: "Adelaide" },
  { zone: "Australia/Canberra", utc: "(UTC+10:00)", name: "Canberra" },
  { zone: "Australia/Melbourne", utc: "(UTC+10:00)", name: "Melbourne" },
  { zone: "Australia/Sydney", utc: "(UTC+10:00)", name: "Sydney" },
  { zone: "Australia/Brisbane", utc: "(UTC+10:00)", name: "Brisbane" },
  { zone: "Australia/Hobart", utc: "(UTC+10:00)", name: "Hobart" },
  { zone: "Asia/Vladivostok", utc: "(UTC+10:00)", name: "Vladivostok" },
  { zone: "Pacific/Guam", utc: "(UTC+10:00)", name: "Guam" },
  { zone: "Asia/Magadan", utc: "(UTC+11:00)", name: "Magadan" },
  { zone: "Pacific/Fiji", utc: "(UTC+12:00)", name: "Fiji" },
  { zone: "Asia/Kamchatka", utc: "(UTC+12:00)", name: "Kamchatka" },
  { zone: "Pacific/Auckland", utc: "(UTC+12:00)", name: "Auckland" },
  { zone: "Pacific/Tongatapu", utc: "(UTC+13:00)", name: "Nukualofa" },
  { zone: "Asia/Nicosia", utc: "(GMT+02:00)", name: "Cyprus" },
  { zone: "America/Havana", utc: "(GMT-05:00)", name: "Cuba" },
  { zone: "Europe/Zagreb", utc: "(GMT+01:00)", name: "Croatia" },
  { zone: "America/Costa_Rica", utc: "(GMT-06:00)", name: "Costa Rica" },
  { zone: "Indian/Comoro", utc: "(GMT+03:00)", name: "Comoros" },
  { zone: "America/Bogota", utc: "(GMT-05:00)", name: "Colombia" },
  { zone: "America/Santiago", utc: "(GMT-03:00)", name: "Chile" },
  { zone: "Africa/Ndjamena", utc: "(GMT+01:00)", name: "Chad" },
  { zone: "Africa/Bangui", utc: "(GMT+01:00)", name: "Central African Republic" },
  { zone: "Africa/Douala", utc: "(GMT+01:00)", name: "Cameroon" },
  { zone: "Africa/Djibouti", utc: "(GMT+03:00)", name: "Djibouti" },
  { zone: "America/Dominica", utc: "(GMT-04:00)", name: "Dominica" },
  { zone: "America/Santo_Domingo", utc: "(GMT-04:00)", name: "Dominican Republic" },
  { zone: "America/Guayaquil", utc: "(GMT-05:00)", name: "Ecuador" },
  { zone: "Africa/Cairo", utc: "(GMT+02:00)", name: "Egypt" },
  { zone: "America/El_Salvador", utc: "(GMT-06:00)", name: "El Salvador" },
  { zone: "Africa/Malabo", utc: "(GMT+01:00)", name: "Equatorial Guinea" },
  { zone: "Africa/Asmara", utc: "(GMT+03:00)", name: "Eritrea" },
  { zone: "Europe/Tallinn", utc: "(GMT+02:00)", name: "Estonia" },
  { zone: "Africa/Mbabane", utc: "(GMT+02:00)", name: "Eswatini" },
  { zone: "Pacific/Fiji", utc: "(GMT+12:00)", name: "Fiji" },
  { zone: "Africa/Libreville", utc: "(GMT+01:00)", name: "Gabon" },
  { zone: "Africa/Banjul", utc: "(GMT+00:00)", name: "Gambia" },
  { zone: "Asia/Tbilisi", utc: "(GMT+04:00)", name: "Georgia" },
  { zone: "America/Grenada", utc: "(GMT-04:00)", name: "Grenada" },
  { zone: "America/Guatemala", utc: "(GMT-06:00)", name: "Guatemala" },
  { zone: "America/Guyana", utc: "(GMT-04:00)", name: "Guyana" },
  { zone: "America/Port-au-Prince", utc: "(GMT-05:00)", name: "Haiti" },
  { zone: "America/Tegucigalpa", utc: "(GMT-06:00)", name: "Honduras" },
  { zone: "Asia/Baghdad", utc: "(GMT+03:00)", name: "Iraq" },
  { zone: "Asia/Amman", utc: "(GMT+03:00)", name: "Jordan" },
  { zone: "Asia/Almaty", utc: "(GMT+06:00)", name: "Kazakhstan" },
  { zone: "Pacific/Tarawa", utc: "(GMT+12:00)", name: "Kiribati" },
  { zone: "Asia/Kuwait", utc: "(GMT+03:00)", name: "Kuwait" },
  { zone: "Asia/Bishkek", utc: "(GMT+06:00)", name: "Kyrgyzstan" },
  { zone: "Asia/Pyongyang", utc: "(GMT+09:00)", name: "North Korea" },
  { zone: "Pacific/Nauru", utc: "(GMT+12:00)", name: "Nauru" },
  { zone: "America/Managua", utc: "(GMT-06:00)", name: "Nicaragua" },
  { zone: "Africa/Niamey", utc: "(GMT+01:00)", name: "Niger" },
  { zone: "Europe/Skopje", utc: "(GMT+01:00)", name: "North Macedonia" },
  { zone: "Asia/Vientiane", utc: "(GMT+07:00)", name: "Laos" },
  { zone: "Europe/Riga", utc: "(GMT+02:00)", name: "Latvia" },
  { zone: "Asia/Beirut", utc: "(GMT+03:00)", name: "Lebanon" },
  { zone: "Africa/Maseru", utc: "(GMT+02:00)", name: "Lesotho" },
  { zone: "Africa/Monrovia", utc: "(GMT+00:00)", name: "Liberia" },
  { zone: "Europe/Vaduz", utc: "(GMT+01:00)", name: "Liechtenstein" },
  { zone: "Europe/Vilnius", utc: "(GMT+02:00)", name: "Lithuania" },
  { zone: "Europe/Luxembourg", utc: "(GMT+01:00)", name: "Luxembourg" },
  { zone: "Africa/Blantyre", utc: "(GMT+02:00)", name: "Malawi" },
  { zone: "Europe/Malta", utc: "(GMT+01:00)", name: "Malta" },
  { zone: "Pacific/Majuro", utc: "(GMT+12:00)", name: "Marshall Islands" },
  { zone: "Pacific/Chuuk", utc: "(GMT+10:00)", name: "Micronesia" },
  { zone: "Europe/Chisinau", utc: "(GMT+02:00)", name: "Moldova" },
  { zone: "Europe/Monaco", utc: "(GMT+01:00)", name: "Monaco" },
  { zone: "Asia/Ulaanbaatar", utc: "(GMT+08:00)", name: "Mongolia" },
  { zone: "Europe/Podgorica", utc: "(GMT+01:00)", name: "Montenegro" },
  { zone: "Asia/Muscat", utc: "(GMT+04:00)", name: "Oman" },
  { zone: "Pacific/Palau", utc: "(GMT+09:00)", name: "Palau" },
  { zone: "America/Panama", utc: "(GMT-05:00)", name: "Panama" },
  { zone: "Pacific/Port_Moresby", utc: "(GMT+10:00)", name: "Papua New Guinea" },
  { zone: "America/Asuncion", utc: "(GMT-04:00)", name: "Paraguay" },
  { zone: "America/Lima", utc: "(GMT-05:00)", name: "Peru" },
  { zone: "America/Puerto_Rico", utc: "(GMT-04:00)", name: "Puerto Rico" },
  { zone: "Asia/Qatar", utc: "(GMT+03:00)", name: "Qatar" },
  { zone: "Africa/Kigali", utc: "(GMT+02:00)", name: "Rwanda" },
  { zone: "America/St_Kitts", utc: "(GMT-04:00)", name: "Saint Kitts and Nevis" },
  { zone: "America/St_Lucia", utc: "(GMT-04:00)", name: "Saint Lucia" },
  { zone: "Pacific/Apia", utc: "(GMT+13:00)", name: "Samoa" },
  { zone: "Europe/San_Marino", utc: "(GMT+01:00)", name: "San Marino" },
  { zone: "Asia/Gaza", utc: "(GMT+02:00)", name: "Palestine" },
  { zone: "Asia/Hebron", utc: "(GMT+02:00)", name: "Palestine" },
  { zone: "Europe/Belgrade", utc: "(GMT+01:00)", name: "Serbia" },
  { zone: "Europe/Bratislava", utc: "(GMT+01:00)", name: "Slovakia" },
  { zone: "Europe/Ljubljana", utc: "(GMT+01:00)", name: "Slovenia" },
  { zone: "Pacific/Guadalcanal", utc: "(GMT+11:00)", name: "Solomon Islands" },
  { zone: "Africa/Mogadishu", utc: "(GMT+03:00)", name: "Somalia" },
  { zone: "Asia/Seoul", utc: "(GMT+09:00)", name: "South Korea" },
  { zone: "America/Paramaribo", utc: "(GMT-03:00)", name: "Suriname" },
  { zone: "Asia/Damascus", utc: "(GMT+02:00)", name: "Syria" },
  { zone: "Asia/Taipei", utc: "(GMT+08:00)", name: "Taiwan" },
  { zone: "Pacific/Fakaofo", utc: "(GMT+13:00)", name: "Tokelau" },
  { zone: "Pacific/Tongatapu", utc: "(GMT+13:00)", name: "Tonga" },
  { zone: "America/Port_of_Spain", utc: "(GMT-04:00)", name: "Trinidad and Tobago" },
  { zone: "Asia/Ashgabat", utc: "(GMT+05:00)", name: "Turkmenistan" },
  { zone: "Pacific/Funafuti", utc: "(GMT+12:00)", name: "Tuvalu" },
  { zone: "Pacific/Efate", utc: "(GMT+11:00)", name: "Vanuatu" },
  { zone: "Europe/Vatican", utc: "(GMT+01:00)", name: "Vatican City" },
  { zone: "America/Caracas", utc: "(GMT-04:00)", name: "Venezuela" },
  { zone: "Asia/Aden", utc: "(GMT+03:00)", name: "Yemen" },
];