"use client";

import { useEffect } from "react";

const countryLangMap: Record<string, string> = {
    US: "en-US",
    GB: "en-GB",
    IN: "hi",
    FR: "fr",
    DE: "de",
    IT: "it",
    ES: "es",
    SA: "ar",
    PK: "ur",
    BD: "bn",
    CN: "zh",
    JP: "ja",
    AF: "fa",
    AL: "sq",
    DZ: "ar",
    AD: "ca",
    AO: "pt",
    AG: "en",
    AR: "es",
    AM: "hy",
    AU: "en-AU",
    AT: "de",
    AZ: "az",
    BS: "en",
    BH: "ar",
    BB: "en",
    BY: "be",
    BE: "nl",
    BZ: "en",
    BJ: "fr",
    BT: "dz",
    BO: "es",
    BA: "bs",
    BW: "en",
    BR: "pt",
    BN: "ms",
    BG: "bg",
    BF: "fr",
    BI: "fr",
    CV: "pt",
    KH: "km",
    CM: "fr",
    CA: "en-CA",
    CF: "fr",
    TD: "fr",
    CL: "es",
    CO: "es",
    KM: "ar",
    CG: "fr",
    CD: "fr",
    CR: "es",
    HR: "hr",
    CU: "es",
    CY: "el",
    CZ: "cs",
    DK: "da",
    DJ: "fr",
    DM: "en",
    DO: "es",
    EC: "es",
    EG: "ar",
    SV: "es",
    GQ: "es",
    ER: "ti",
    EE: "et",
    SZ: "en",
    ET: "am",
    FJ: "en",
    FI: "fi",
    GA: "fr",
    GM: "en",
    GE: "ka",
    GH: "en",
    GR: "el",
    GD: "en",
    GT: "es",
    GN: "fr",
    GW: "pt",
    GY: "en",
    HT: "ht",
    HN: "es",
    HU: "hu",
    IS: "is",
    ID: "id",
    IR: "fa",
    IQ: "ar",
    IE: "en",
    IL: "he",
    JM: "en",
    JO: "ar",
    KZ: "kk",
    KE: "en",
    KI: "en",
    KP: "ko",
    KR: "ko",
    KW: "ar",
    KG: "ky",
    LA: "lo",
    LV: "lv",
    LB: "ar",
    LS: "en",
    LR: "en",
    LY: "ar",
    LI: "de",
    LT: "lt",
    LU: "lb",
    MG: "mg",
    MW: "en",
    MY: "ms",
    MV: "dv",
    ML: "fr",
    MT: "mt",
    MH: "mh",
    MR: "ar",
    MU: "en",
    MX: "es",
    FM: "en",
    MD: "ro",
    MC: "fr",
    MN: "mn",
    ME: "sr",
    MA: "ar",
    MZ: "pt",
    MM: "my",
    NA: "en",
    NR: "en",
    NP: "ne",
    NL: "nl",
    NZ: "en-NZ",
    NI: "es",
    NE: "fr",
    NG: "en",
    MK: "mk",
    NO: "no",
    OM: "ar",
    PA: "es",
    PG: "en",
    PY: "es",
    PE: "es",
    PH: "tl",
    PL: "pl",
    PT: "pt",
    QA: "ar",
    RO: "ro",
    RU: "ru",
    RW: "rw",
    KN: "en",
    LC: "en",
    VC: "en",
    WS: "sm",
    SM: "it",
    ST: "pt",
    SN: "fr",
    RS: "sr",
    SC: "en",
    SL: "en",
    SG: "en",
    SK: "sk",
    SI: "sl",
    SB: "en",
    SO: "so",
    ZA: "en-ZA",
    SS: "en",
    LK: "si",
    SD: "ar",
    SR: "nl",
    SE: "sv",
    CH: "de",
    SY: "ar",
    TW: "zh-TW",
    TJ: "tg",
    TZ: "sw",
    TH: "th",
    TL: "pt",
    TG: "fr",
    TO: "to",
    TT: "en",
    TN: "ar",
    TR: "tr",
    TM: "tk",
    TV: "en",
    UG: "en",
    UA: "uk",
    AE: "ar",
    UY: "es",
    UZ: "uz",
    VU: "bi",
    VA: "la",
    VE: "es",
    VN: "vi",
    YE: "ar",
  };

const HtmlLangSetter = () => {
  useEffect(() => {
    const setLang = async () => {
      try {
        const res = await fetch("https://pro.ip-api.com/json/?key=kHg84ht9eNasCRN");
        const data = await res.json();

        const countryCode = data?.countryCode;
        const lang = countryLangMap[countryCode] || "en";

        document.documentElement.lang = lang;
      } catch (error) {
        console.error("Error setting HTML lang:", error);
      }
    };

    setLang();
  }, []);

  return null; 
};

export default HtmlLangSetter;