name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  SFTP-Deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy using SFTP
        uses: shahrukhdev/sftp-deploy@v1.2
        with:
          host: business76.web-hosting.com
          port: 21098
          username: teckezxd
          password: ';Riy=O$=VQv%'
          localPath: ./                          # Local project root
          remotePath: /home/teckezxd/globalsalah.com/  # **Exact remote path**
          dryRun: false
          deleteRemoteFiles: false
          sftpOnly: true
          exclude: |
            node_modules
            .git
            .next/cache
            *.map
