name: FTP Deploy (Hardcoded)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: FTP Deploy (hardcoded creds)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.teckteam.org
          username: global_sallaahh266@globalsalah.com
          password: 2O7O-FjIapDC
          port: 21
          protocol: ftp
          server-dir: /home/teckezxd/globalsalah.com/
