name: Deploy Next.js app to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy .next and public folders via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: business76.web-hosting.com
          username: teckezxd
          password: ';Riy=O$=VQv%'
          port: 21098
          source: |
            .next
            public
          target: /home/teckezxd/globalsalah.com/
          recursive: true
