name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  SFTP-Deploy-Action:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ""
          REMOTE_HOST: business76.web-hosting.com
          REMOTE_PORT: 21098
          REMOTE_USER: teckezxd
          REMOTE_PASSWORD: ';Riy=O$=VQv%'
          SOURCE: "./"
          TARGET: "/home/teckezxd/globalsalah.com/"
          EXCLUDE: |
            node_modules
            .git
            .next/cache
            *.map
          ARGS: "-o StrictHostKeyChecking=no"
