name: Deploy Next.js 15 to cPanel

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Next.js 15
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Prepare files for deployment
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy Next.js output to deploy directory
        cp -r .next deploy/
        cp -r public deploy/
        cp next.config.* deploy/ 2>/dev/null || :
        cp package.json deploy/
        
        # Create .env.production if needed
        touch deploy/.env.production
        
        # Create production node_modules (smaller than dev dependencies)
        cd deploy
        npm install --production
        
        echo "Files prepared for deployment:"
        find . -type f | wc -l
        
    - name: Deploy to cPanel via FTP - Core Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 162.0.232.190
        username: global_sallaahh266@globalsalah.com
        password: 2O7O-FjIapDC
        local-dir: ./deploy/
        server-dir: /home/teckezxd/globalsalah.com/
        exclude: |
          **/.git*
          **/node_modules/**
          **/.next/cache/**
        timeout: 600000 # 10 minutes
        port: 21
        protocol: ftp
        log-level: verbose
        dangerous-clean-slate: false
        dry-run: false
        state-name: .ftp-deploy-sync-state.json
        strict: false
        security: loose
        retries: 5
        max-concurrent-connections: 3
        
    - name: Verify deployment
      run: |
        echo "✅ Next.js 15 website deployed successfully to globalsalah.com"
        echo "🚀 Deployment completed at $(date)"
