name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload to FTP (clean .next before upload)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 192.250.232.90
          username: testinglc2@testing.lc2swansea.online
          password: LX3BAtubA4
          port: 21
          protocol: ftp
          server-dir: /                 # ⚠️ Must be root of your server path
          local-dir: ./                # Upload from project root
          exclude: |
            **/node_modules/**
            **/.git*
            **/.next/cache/**
            **/*.map
          delete: true                 # 🧹 Remove unmatched files on server
          delete-excluded: true        # 🔥 Delete old .next on server even if excluded
