name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload to SFTP (clean .next before upload)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: business76.web-hosting.com
          username: teckezxd
          password: ';Riy=O$=VQv%'
          port: 21098
          protocol: sftp
          server-dir: /home/teckezxd/globalsalah.com/    # exact remote path
          local-dir: ./                                 # project root
          exclude: |
            **/node_modules/**
            **/.git*
            **/.next/cache/**
            **/*.map
          delete: true
          delete-excluded: true
